if __name__ == "__main__":
    print("HiddenEdge Engine v1.0 | SB3PM")
# =========================================
# HiddenEdge / SB3PM Advisory & Services Ltd
# Author: Stephan Bals
# © 2026 SB3PM Advisory & Services Ltd
#
# This code is proprietary and confidential.
# Unauthorized use, distribution, or replication is prohibited.
# =========================================

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO


def generate_docx(cv_text, template="corporate"):

    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    if template == "consultant":
        header_size = 18
        spacing = 1
    elif template == "executive":
        header_size = 20
        spacing = 2
    else:  # corporate
        header_size = 16
        spacing = 1

    title = doc.add_paragraph()
    run = title.add_run("CURRICULUM VITAE")
    run.bold = True
    run.font.size = Pt(header_size)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("")

    lines = cv_text.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            doc.add_paragraph("")
            continue

        if line.isupper() and len(line) < 40:
            p = doc.add_paragraph()
            r = p.add_run(line)
            r.bold = True
            r.font.size = Pt(13 + spacing)
            continue

        if line.startswith("-") or line.startswith("•"):
            doc.add_paragraph(line[1:].strip(), style='List Bullet')
            continue

        doc.add_paragraph(line)

    doc.add_paragraph("")
    footer = doc.add_paragraph("Generated by HiddenEdge")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    file_stream = BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)

    return file_stream.getvalue()